package com.example.keith.myapplication;

import android.app.Activity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;


public class MyActivity extends Activity {




    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my);//this makes it show the xml file.
        //R is auto generated by Android SDK, its the link between xml and java

        //first gets started, calls this first


        //gets the value from the first textbox, coverts and puts into second textbox
        final EditText centimetersItem = (EditText) findViewById(R.id.cents_textbox);
        final EditText inchesItem = (EditText) findViewById(R.id.inches_textbox);

        Button buttonConvert = (Button) findViewById(R.id.button);

        buttonConvert.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                double centimeters = Double.valueOf(centimetersItem.getText().toString());
                double inches = centimeters * 0.393700787;
                inchesItem.setText(String.valueOf(inches));
            }
        });
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.my, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();
        if (id == R.id.action_settings) {
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
}
